export type RoleCode =
  | "SUPER_ADMIN"
  | "ADMIN"
  | "SUPPORT"
  | "FINANCE"
  | "CONTENT"
  | "MARKETING"
  | "DEVELOPER";

export type PermissionKey =
  | "users.view.any"
  | "users.create.any"
  | "users.update.any"
  | "users.delete.any"
  | "roles.view"
  | "roles.manage"
  | "clients.view.any"
  | "clients.create.any"
  | "clients.update.any"
  | "clients.delete.any"
  | "billing.view"
  | "billing.refund"
  | "dashboard.view"
  | "settings.update"
  | "analytics.view"
  | "audit.view"
  | "templates.view"
  | "templates.create"
  | "templates.publish"
  | "sites.manage";
