import type { PermissionKey } from "@/types/rbac";

export const PERMISSIONS = {
  USERS_VIEW: "users.view.any" as PermissionKey,
  USERS_CREATE: "users.create.any" as PermissionKey,
  USERS_UPDATE: "users.update.any" as PermissionKey,
  USERS_DELETE: "users.delete.any" as PermissionKey,
  ROLES_VIEW: "roles.view" as PermissionKey,
  ROLES_MANAGE: "roles.manage" as PermissionKey,
  CLIENTS_VIEW: "clients.view.any" as PermissionKey,
  CLIENTS_CREATE: "clients.create.any" as PermissionKey,
  CLIENTS_UPDATE: "clients.update.any" as PermissionKey,
  CLIENTS_DELETE: "clients.delete.any" as PermissionKey,
  BILLING_VIEW: "billing.view" as PermissionKey,
  BILLING_REFUND: "billing.refund" as PermissionKey,
  DASHBOARD_VIEW: "dashboard.view" as PermissionKey,
  SETTINGS_UPDATE: "settings.update" as PermissionKey,
  ANALYTICS_VIEW: "analytics.view" as PermissionKey,
  AUDIT_VIEW: "audit.view" as PermissionKey,
  TEMPLATES_VIEW: "templates.view" as PermissionKey,
  TEMPLATES_CREATE: "templates.create" as PermissionKey,
  TEMPLATES_PUBLISH: "templates.publish" as PermissionKey,
  TEMPLATES_UPDATE_OWN: "templates.update.own" as PermissionKey,
  TEMPLATES_UPDATE_ANY: "templates.update.any" as PermissionKey,
  TEMPLATES_DELETE_OWN: "templates.delete.own" as PermissionKey,
  TEMPLATES_DELETE_ANY: "templates.delete.any" as PermissionKey,
  SITES_MANAGE: "sites.manage" as PermissionKey,
  CATEGORIES_VIEW: "categories.view" as PermissionKey,
  CATEGORIES_CREATE: "categories.create" as PermissionKey,
  CATEGORIES_UPDATE: "categories.update" as PermissionKey,
  CATEGORIES_DELETE: "categories.delete" as PermissionKey,
} as const;
